// Copyright (C) 2006 NISHIMURA Tsuyoshi
// License: GPL v2 or (at your option) any later version
/** @file
 * 
 * メインのフレームクラス
 * 
 * $Date: 2007/10/31 16:10:00 $
 */
// -*- C++ -*- generated by wxGlade 0.4cvs on Sun Aug 21 17:40:35 2005

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DICMAINFRAME_H
#define DICMAINFRAME_H

#include <wx/confbase.h>

// begin wxGlade: ::dependencies
#include <wx/splitter.h>
#include <wx/listctrl.h>
// end wxGlade

#include <eb/eb.h>
#include "DicPropertyGrid.h"
#include "DicHtmlWindow.h"
#include "DicMultiCandidates.h"
#include "DicSettingDialog.h"

class DicSubbook;

/**
 * メインのフレームクラス
 */
class DicMainFrame: public wxFrame
{
public:
	enum {
		SEARCH_WORD,
		SEARCH_END_WORD,
		SEARCH_EXACT_WORD,
		SEARCH_KEYWORD,
		SEARCH_CROSS,
		SEARCH_MULTI,
		BOOK_MENU,
		BOOK_COPYRIGHT
	};
	
    // begin wxGlade: DicMainFrame::ids
    // end wxGlade

    DicMainFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);
	virtual ~DicMainFrame();

protected:
#ifdef __WXMSW__
	virtual bool MSWTranslateMessage(WXMSG* pMsg);
#endif
	virtual void OnCharHook(wxKeyEvent& event);
    virtual void OnExit(wxCommandEvent& event);
    virtual void OnAbout(wxCommandEvent& event);
    virtual void OnSearchMethod(wxCommandEvent& event);
    virtual void OnUpdateSearchMethod(wxUpdateUIEvent& event);
    virtual void OnOption(wxCommandEvent& event);
    virtual void OnImportSettings(wxCommandEvent& event);
    virtual void OnExportSettings(wxCommandEvent& event);
    virtual void OnSearchBook(wxCommandEvent& event);
    virtual void OnSearch(wxCommandEvent& event);
    virtual void Search();
    virtual void OnBack(wxCommandEvent& event);
    virtual void OnForward(wxCommandEvent& event);
    virtual void OnUp(wxCommandEvent& event);
    virtual void OnDown(wxCommandEvent& event);
    virtual void OnDicChoice(wxCommandEvent& event);
    virtual void OnKeywordCombo(wxCommandEvent& event);
    virtual void OnMultiTypeChoice(wxCommandEvent& event);
    virtual void OnMultiKeysGridClicked(wxPropertyGridEvent& event);
    virtual void OnMultiKeysGridButton(wxCommandEvent& event);
    virtual void OnMultiKeysMenu(wxCommandEvent& event);
    virtual void OnHitListItemSelected(wxListEvent& event);
    
    // begin wxGlade: DicMainFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade
    
	virtual void Customize();
	virtual void LoadConfig(wxConfigBase* config = NULL);
	virtual void SaveConfig(wxConfigBase* config = NULL);
	virtual void UpdateSubbooks();
	virtual void ShowMultiSearchList(int selection = 0);
	virtual void ShowMultiSearchEntry();
	virtual void PopupMultiCandidates();
	virtual wxMenu* MultiCandudatesMenu(DicSubbook* subbook, EB_Position pos);
	virtual DicSubbook* GetCurSubbook();
    
protected:
    // begin wxGlade: DicMainFrame::attributes
    wxMenuBar* m_menubar;
    wxStatusBar* m_statusbar;
    wxToolBar* m_toolbar;
    wxChoice* m_dicChoice;
    wxPanel* m_leftPane1;
    wxComboBox* m_keywordCombo;
    wxPanel* m_leftPane2;
    wxSplitterWindow* m_leftSplitter;
    wxChoice* m_multiTypeChoice;
    DicPropertyGrid* m_multiKeysGrid;
    wxPanel* m_leftPane3;
    wxListCtrl* m_hitList;
    wxPanel* m_leftPane4;
    wxSplitterWindow* m_multiKeysSplitter;
    wxPanel* m_leftPane;
    DicHtmlWindow* m_htmlWin;
    wxPanel* m_rightPane;
    wxSplitterWindow* m_splitter;
    // end wxGlade

    int m_searchMethod;
    int m_multiKeysSashPos;
    
    DicMultiCandidates m_multiCandidates;
    
    DicSettingDialog* m_settingDialog;
    
    DECLARE_EVENT_TABLE()

}; // wxGlade: end class


#endif // DICMAINFRAME_H
