// Copyright (C) 2006-2007 NISHIMURA Tsuyoshi
// License: GPL v2 or (at your option) any later version
/** @file
 * 
 * 設定ダイアログクラス
 * 
 * $Date: 2007/10/31 16:12:34 $
 */
// -*- C++ -*- generated by wxGlade 0.4 on Tue Jun 20 20:17:06 2006

#include <wx/wx.h>
#include <wx/image.h>

#ifndef DICSETTINGDIALOG_H
#define DICSETTINGDIALOG_H

#include "DicPropertyGrid.h"
#include "DicSubbooks.h"

// begin wxGlade: ::dependencies
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
// end wxGlade

/**
 * 設定ダイアログクラス
 */
class DicSettingDialog: public wxDialog
{
public:
    // begin wxGlade: DicSettingDialog::ids
    // end wxGlade

    DicSettingDialog(wxWindow* parent, int id, const wxString& title,
    	const wxPoint& pos = wxDefaultPosition,
    	const wxSize& size = wxDefaultSize,
    	long style = wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER);
	~DicSettingDialog();
	
protected:
	virtual void OnCharHook(wxKeyEvent& event);
	virtual void OnOK(wxCommandEvent& event);
	virtual void OnCMenuDicList(wxContextMenuEvent& event);
	virtual void OnCMenuGroupTree(wxContextMenuEvent& event);
	virtual void OnCMenuSCList(wxContextMenuEvent& event);
	virtual void OnDicListUp(wxCommandEvent& event);
	virtual void OnDicListDown(wxCommandEvent& event);
	virtual void OnDicListEdit(wxCommandEvent& event);
	virtual void OnDicListDelete(wxCommandEvent& event);
	
    // begin wxGlade: DicSettingDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade
    
    virtual void Customize();

 public:
    virtual void LoadConfig();
    virtual void SaveConfig();

protected:    
    virtual void ShowDicListItem(long item);

protected:
    // begin wxGlade: DicSettingDialog::attributes
    DicPropertyGrid* m_grid;
    wxPanel* m_note_pane_1;
    wxListCtrl* m_dicList;
    wxPanel* m_note_pane_2;
    wxTreeCtrl* m_groupTree;
    wxPanel* m_note_pane_3;
    wxListCtrl* m_scList;
    wxPanel* m_note_pane_4;
    wxNotebook* m_note;
    wxButton* m_ok;
    wxButton* m_cancel;
    // end wxGlade
    
    // プロパティグリッドのID
    wxPGId m_pageMaxResults;
    wxPGId m_pageMaxBytes;
    wxPGId m_searchMaxResults;
    wxPGId m_mainFrameMaximize;
//    wxPGId m_mainFrameX;
//    wxPGId m_mainFrameY;
    wxPGId m_mainFrameWidth;
    wxPGId m_mainFrameHeight;
    wxPGId m_toolbarSearchMethod;
    wxPGId m_splitterSashPosition;
    wxPGId m_leftSplitterSashPosition;
    wxPGId m_dicChoiceSelection;
	wxPGId m_multiKeysSplitterSashPosition;
	wxPGId m_multiTypeChoiceSelection;
    wxPGId m_hitListColumnWidth0;
    wxPGId m_hitListColumnWidth1;
    wxPGId m_htmlWinFontFaceFixed;
    wxPGId m_htmlWinFontFaceNormal;
    wxPGId m_htmlWinFontsSize0;
    wxPGId m_htmlWinFontsSize1;
    wxPGId m_htmlWinFontsSize2;
    wxPGId m_htmlWinFontsSize3;
    wxPGId m_htmlWinFontsSize4;
    wxPGId m_htmlWinFontsSize5;
    wxPGId m_htmlWinFontsSize6;
    wxPGId m_htmlHead;
    wxPGId m_htmlFoot;
    wxPGId m_keywordHead;
    wxPGId m_keywordFoot;
    wxPGId m_decorationHead;
    wxPGId m_decorationFoot;
    wxPGId m_emphasisHead;
    wxPGId m_emphasisFoot;
    wxPGId m_superscriptHead;
    wxPGId m_superscriptFoot;
    wxPGId m_subscriptHead;
    wxPGId m_subscriptFoot;
    wxPGId m_newLine;
    wxPGId m_noNewlineHead;
    wxPGId m_noNewlineFoot;

	// ポップアップメニュー
	wxMenu m_menuDicList;
	wxMenu m_menuGroupTree;
	wxMenu m_menuSCList;
    
    // 編集用データ
    DicSubbooks m_subbooks;
    
    DECLARE_EVENT_TABLE()
    
}; // wxGlade: end class


#endif // DICSETTINGDIALOG_H
