// Copyright (C) 2006-2007 NISHIMURA Tsuyoshi
/*
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/

/** @file
 * 
 * digdicメイン
 * 
 * $Date: 2007/10/31 16:14:19 $
 */
// -*- C++ -*- generated by wxGlade 0.4cvs on Sun Aug 21 17:05:13 2005

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/stdpaths.h>
#include <wx/filename.h>
#include <wx/fileconf.h>
#include "DicMainFrame.h"
#include "DicShare.h"

/**
 * アプリケーションクラス
 */
class DicApp: public wxApp {
public:
    bool OnInit();
    int OnExit();
private:
	wxLocale m_locale;
};

IMPLEMENT_APP(DicApp);

/**
 * 初期処理
 */
bool DicApp::OnInit()
{
	// カレントフォルダを実行ファイルの場所にする。
	::wxSetWorkingDirectory(::wxPathOnly(argv[0]));

	// メッセージカタログの設定をする。
	m_locale.Init(wxLANGUAGE_DEFAULT);
	m_locale.AddCatalogLookupPathPrefix(wxT("locale"));
	m_locale.AddCatalog(wxT("digdic"));
	
#if 0
	// 設定ファイルの設定をする。
	wxString iniDir = wxStandardPaths::Get().GetUserDataDir();
	wxFileName::Mkdir(iniDir, 0777, wxPATH_MKDIR_FULL);
	wxFileName fn = wxFileName(iniDir, GetAppName(), wxT("ini"));
	DicShare::iniFile = fn.GetFullPath();
	wxFileConfig* config = new wxFileConfig(
		wxEmptyString,
		wxEmptyString,
		DicShare::iniFile,
		wxEmptyString,
		wxCONFIG_USE_LOCAL_FILE,
		*wxConvCurrent);
#else
	// レジストリを使う。
	wxConfig* config = new wxConfig(
		wxT("digdic"),
		wxT("digdic"),
		wxEmptyString,
		wxEmptyString,
		wxCONFIG_USE_LOCAL_FILE);
#endif
	wxConfigBase::Set(config);

	// 共通の設定を読み込む。
	DicShare::LoadConfig();
	
    wxInitAllImageHandlers();
    DicMainFrame* main_frame = new DicMainFrame(0, -1, wxT(""));
    SetTopWindow(main_frame);
    main_frame->Show();
    return true;
}

/**
 * 終了処理
 */
int DicApp::OnExit()
{
	// 共通の設定を保存する。
	DicShare::SaveConfig();
	
	return wxApp::OnExit();
}
